language: python

sudo: false

python:
- 3.6

script: 
- pip3 install pandas synapseclient
- python3 GenerateAndSendStorageReport.py -e {SYNAPSE_USERNAME} -k ${SYNAPSE_API_KEY} -r ${NOTIFICATION_PRINCIPAL_ID} -t ${TABLE_SYNAPSE_ID}
