language: python

sudo: false

python:
- 3.7

script: 
- pip3 install synapseclient
- python3 GenerateAndSendStorageReport.py python3 GenerateAndSendStorageReport.py -e {SYNAPSE_USERNAME} -k ${SYNAPSE_API_KEY} -r ${NOTIFICATION_PRINCIPAL_ID} ${TABLE_SYNAPSE_ID}
